version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env.docker
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sh -c "pnpm install && pnpm exec prisma generate && pnpm dev"
    volumes:
      - ./apps/api:/app
      - /app/node_modules

  client:
    build: ./apps/client
    ports:
      - "5173:5173"
    command: pnpm dev --host
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pgdata:
